# Jekyll configuration
title: Minh Mốc Meo
description: Đi để đi
url: https://minh.xuvi.vn
baseurl: ""
theme: just-the-docs
language: vi
author:
  name: Minh Mốc Meo
  email: minhxuvi@gmail.com
  url: https://minh.xuvi.vn
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
