# Jekyll configuration
title: Minh Mốc Meo
description: Đi để đi
baseurl: ""
remote_theme: just-the-docs/just-the-docs
url: https://minh.xuvi.vn
language: vi
author:
  name: Minh Mốc Meo
  email: minhxuvi@gmail.com
  url: https://minh.xuvi.vn
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
