name: "Publish from minhxuvi.wiki"

on:
  schedule:
    - cron: "0 0 * * *" # runs every day at midnight
  workflow_dispatch: # allows manual triggering of the workflow

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout minhxuvi
        uses: actions/checkout@v4
        with:
          repository: minhxuvi/minhxuvi
          path: minhxuvi

      - name: Checkout github page
        uses: actions/checkout@v4
        with:
          repository: minhxuvi/minhxuvi.github.io
          submodules: 'recursive'
          path: minhxuvi.github.io

      - name: Copy wiki to main repository
        run: |
          cp -r minhxuvi/* minhxuvi.github.io

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Push to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          cd minhxuvi.github.io
          git submodule update --init --recursive
          cd wiki
          git fetch
          git checkout origin/master
          cd ..
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add .
            git commit -m "Update wiki - $(date +%Y-%m-%d)"
            git push https://${GITHUB_TOKEN}@github.com/minhxuvi/minhxuvi.github.io.git HEAD:main
          fi